// ================================================================
// LAPTOPS DATA - LaptopMatchVN / EasyLap
// 15 laptop mẫu cho demo, mỗi máy có đầy đủ trường mới
// ================================================================

const laptops = [
    {
        id: "l1",
        name: "Acer Aspire 3 A315",
        brand: "Acer",
        price: 9900000,
        priceFormatted: "9.900.000đ",
        cpu: "Intel Core i3-1215U",
        cpuLevel: 1, // 1=basic, 2=mid, 3=strong, 4=very strong
        ram: "8GB",
        ramValue: 8,
        ssd: "512GB",
        ssdValue: 512,
        gpu: "Intel UHD Graphics",
        hasDiscreteGPU: false,
        screen: "15.6 inch FHD",
        hasColorScreen: false,
        battery: "40Wh",
        batteryLevel: 1, // 1=weak, 2=ok, 3=good
        weight: "1.7 kg",
        weightValue: 1.7,
        weightLevel: 2, // 1=very light, 2=normal, 3=heavy
        warranty: "12 tháng",
        image: "https://placehold.co/400x300/e2e8f0/64748b?text=Acer+Aspire+3",
        suitableFor: ["firsttime", "finance", "office"],
        tags: ["value_for_money", "easy_use", "office", "ssd_512gb"],
        pros: [
            "Giá rẻ nhất phân khúc, dễ tiếp cận với sinh viên hoặc người mua lần đầu.",
            "SSD 512GB rộng rãi để lưu tài liệu, bài học.",
            "Màn hình 15.6 inch lớn, dễ nhìn khi làm Excel hay PowerPoint."
        ],
        cons: [
            "CPU i3 khá yếu, sẽ hơi chậm khi mở nhiều phần mềm cùng lúc.",
            "Vỏ nhựa, thiết kế bình thường, không nổi bật.",
            "Pin chỉ dùng được khoảng 4–5 tiếng."
        ],
        upgradeable: true,
        scoreByUseCase: { it: 30, finance: 65, design: 20, office: 68, gaming: 10, creator: 15, firsttime: 70 }
    },
    {
        id: "l2",
        name: "Lenovo IdeaPad Slim 5",
        brand: "Lenovo",
        price: 16500000,
        priceFormatted: "16.500.000đ",
        cpu: "Intel Core i5-1335U",
        cpuLevel: 2,
        ram: "16GB",
        ramValue: 16,
        ssd: "512GB",
        ssdValue: 512,
        gpu: "Intel Iris Xe",
        hasDiscreteGPU: false,
        screen: "14 inch WUXGA OLED",
        hasColorScreen: true,
        battery: "56Wh",
        batteryLevel: 3,
        weight: "1.46 kg",
        weightValue: 1.46,
        weightLevel: 1,
        warranty: "24 tháng",
        image: "https://placehold.co/400x300/e2e8f0/64748b?text=IdeaPad+Slim+5",
        suitableFor: ["finance", "office", "it", "firsttime"],
        tags: ["lightweight", "battery_good", "office", "color_screen", "ram_16gb", "ssd_512gb", "coding", "balanced"],
        pros: [
            "RAM 16GB giúp mở nhiều phần mềm cùng lúc mà không bị chậm.",
            "Màn hình OLED màu sắc cực đẹp, xem phim hay thiết kế Canva rất sướng.",
            "Pin trâu, dùng văn phòng được 7–8 tiếng không cắm sạc.",
            "Nhẹ 1.46kg, dễ mang đi học hằng ngày."
        ],
        cons: [
            "Không có card rời nên chơi game nặng sẽ bị giật lag.",
            "RAM hàn cứng trên bo mạch, không nâng cấp thêm được."
        ],
        upgradeable: false,
        scoreByUseCase: { it: 70, finance: 85, design: 60, office: 82, gaming: 20, creator: 50, firsttime: 78 }
    },
    {
        id: "l3",
        name: "Asus Vivobook 15X OLED",
        brand: "Asus",
        price: 18900000,
        priceFormatted: "18.900.000đ",
        cpu: "AMD Ryzen 7 7730U",
        cpuLevel: 3,
        ram: "16GB",
        ramValue: 16,
        ssd: "512GB",
        ssdValue: 512,
        gpu: "AMD Radeon Graphics",
        hasDiscreteGPU: false,
        screen: "15.6 inch FHD OLED",
        hasColorScreen: true,
        battery: "50Wh",
        batteryLevel: 2,
        weight: "1.6 kg",
        weightValue: 1.6,
        weightLevel: 2,
        warranty: "24 tháng",
        image: "https://placehold.co/400x300/e2e8f0/64748b?text=Vivobook+15X",
        suitableFor: ["it", "finance", "design", "office", "creator"],
        tags: ["cpu_strong", "ram_16gb", "ssd_512gb", "color_screen", "office", "coding", "design", "balanced"],
        pros: [
            "CPU Ryzen 7 mạnh mẽ, chạy mượt mà mọi phần mềm văn phòng hay lập trình.",
            "Màn hình OLED 15.6 inch đẹp, màu sắc rực rỡ, phù hợp chỉnh ảnh hay thiết kế 2D.",
            "RAM 16GB thoải mái mở nhiều ứng dụng cùng lúc.",
            "Có thể nâng cấp thêm SSD."
        ],
        cons: [
            "Không có card rời, không phù hợp chơi game nặng.",
            "Pin chỉ ở mức trung bình, tầm 5–6 tiếng văn phòng."
        ],
        upgradeable: true,
        scoreByUseCase: { it: 80, finance: 78, design: 72, office: 75, gaming: 25, creator: 65, firsttime: 72 }
    },
    {
        id: "l4",
        name: "HP Pavilion 14",
        brand: "HP",
        price: 14500000,
        priceFormatted: "14.500.000đ",
        cpu: "Intel Core i5-1235U",
        cpuLevel: 2,
        ram: "8GB",
        ramValue: 8,
        ssd: "512GB",
        ssdValue: 512,
        gpu: "Intel Iris Xe",
        hasDiscreteGPU: false,
        screen: "14 inch FHD",
        hasColorScreen: false,
        battery: "43Wh",
        batteryLevel: 2,
        weight: "1.4 kg",
        weightValue: 1.4,
        weightLevel: 1,
        warranty: "12 tháng",
        image: "https://placehold.co/400x300/e2e8f0/64748b?text=HP+Pavilion+14",
        suitableFor: ["finance", "office", "firsttime"],
        tags: ["lightweight", "office", "ssd_512gb", "value_for_money", "easy_use"],
        pros: [
            "Thiết kế kim loại sang trọng, rất đẹp trong tầm giá.",
            "Nhẹ 1.4kg, dễ mang đi học hay đến văn phòng.",
            "Bàn phím gõ êm, phím di chuột chính xác."
        ],
        cons: [
            "RAM 8GB hơi ít nếu mở nhiều tab hoặc dùng nhiều ứng dụng cùng lúc.",
            "Pin khoảng 5–6 tiếng, không quá trâu.",
            "Không chơi được game nặng, không làm đồ họa chuyên nghiệp."
        ],
        upgradeable: true,
        scoreByUseCase: { it: 50, finance: 75, design: 30, office: 72, gaming: 10, creator: 20, firsttime: 74 }
    },
    {
        id: "l5",
        name: "MacBook Air M1",
        brand: "Apple",
        price: 18500000,
        priceFormatted: "18.500.000đ",
        cpu: "Apple M1",
        cpuLevel: 3,
        ram: "8GB",
        ramValue: 8,
        ssd: "256GB",
        ssdValue: 256,
        gpu: "7-core GPU tích hợp",
        hasDiscreteGPU: false,
        screen: "13.3 inch Retina",
        hasColorScreen: true,
        battery: "49.9Wh",
        batteryLevel: 3,
        weight: "1.29 kg",
        weightValue: 1.29,
        weightLevel: 1,
        warranty: "12 tháng",
        image: "https://placehold.co/400x300/e2e8f0/64748b?text=MacBook+Air+M1",
        suitableFor: ["finance", "office", "creator", "design"],
        tags: ["lightweight", "battery_good", "color_screen", "durable", "easy_use", "office", "design"],
        pros: [
            "Pin cực trâu, dùng cả ngày làm việc không cần sạc.",
            "Máy tuyệt đối im lặng khi hoạt động, không có quạt tản nhiệt.",
            "Màn hình Retina sắc nét, màu chuẩn, loa cực hay.",
            "Nhẹ nhất phân khúc (1.29kg), cầm bằng một tay."
        ],
        cons: [
            "SSD chỉ 256GB, rất dễ đầy nếu lưu nhiều file.",
            "Không thể nâng cấp RAM hay SSD.",
            "Hệ điều hành macOS cần thời gian làm quen nếu quen Windows.",
            "Không chơi được game Windows như LOL, Valorant."
        ],
        upgradeable: false,
        scoreByUseCase: { it: 55, finance: 80, design: 68, office: 82, gaming: 5, creator: 70, firsttime: 72 }
    },
    {
        id: "l6",
        name: "Acer Nitro V ANV15",
        brand: "Acer",
        price: 21900000,
        priceFormatted: "21.900.000đ",
        cpu: "Intel Core i5-13420H",
        cpuLevel: 3,
        ram: "16GB",
        ramValue: 16,
        ssd: "512GB",
        ssdValue: 512,
        gpu: "RTX 4050 6GB",
        hasDiscreteGPU: true,
        screen: "15.6 inch FHD 144Hz",
        hasColorScreen: false,
        battery: "57Wh",
        batteryLevel: 2,
        weight: "2.1 kg",
        weightValue: 2.1,
        weightLevel: 3,
        warranty: "12 tháng",
        image: "https://placehold.co/400x300/e2e8f0/64748b?text=Acer+Nitro+V",
        suitableFor: ["gaming", "it", "creator"],
        tags: ["gpu_dedicated", "ram_16gb", "ssd_512gb", "cpu_strong", "high_refresh_rate", "cooling_good", "coding"],
        pros: [
            "Card RTX 4050 chơi tốt hầu hết game hiện tại: Valorant, GTA V, Genshin đều mượt.",
            "CPU i5-13420H mạnh, chạy cả máy ảo lẫn lập trình không vấn đề gì.",
            "RAM 16GB, dễ nâng cấp thêm SSD sau này.",
            "Màn hình 144Hz cực mượt khi chơi game."
        ],
        cons: [
            "Máy khá nặng (2.1kg) và cục sạc to, không tiện mang đi mỗi ngày.",
            "Pin tụt rất nhanh khi chơi game, chỉ khoảng 2–3 tiếng.",
            "Màn hình màu sắc không đẹp bằng OLED, không phù hợp thiết kế chuyên nghiệp."
        ],
        upgradeable: true,
        scoreByUseCase: { it: 82, finance: 30, design: 45, office: 35, gaming: 88, creator: 72, firsttime: 40 }
    },
    {
        id: "l7",
        name: "Lenovo Legion 5 Gen 8",
        brand: "Lenovo",
        price: 32000000,
        priceFormatted: "32.000.000đ",
        cpu: "Intel Core i7-13700H",
        cpuLevel: 4,
        ram: "16GB",
        ramValue: 16,
        ssd: "512GB",
        ssdValue: 512,
        gpu: "RTX 4060 8GB",
        hasDiscreteGPU: true,
        screen: "15.6 inch 2K 165Hz",
        hasColorScreen: false,
        battery: "80Wh",
        batteryLevel: 2,
        weight: "2.4 kg",
        weightValue: 2.4,
        weightLevel: 3,
        warranty: "24 tháng",
        image: "https://placehold.co/400x300/e2e8f0/64748b?text=Legion+5",
        suitableFor: ["gaming", "creator", "it", "design"],
        tags: ["gpu_dedicated", "cpu_strong", "ram_16gb", "ssd_512gb", "cooling_good", "high_refresh_rate", "durable", "coding"],
        pros: [
            "RTX 4060 8GB cực mạnh, chiến tốt mọi game kể cả game AAA như PUBG, Warzone ở thiết lập cao.",
            "CPU i7-13700H hàng đầu, render video cũng rất nhanh.",
            "Màn hình 2K 165Hz vừa sắc nét vừa cực mượt.",
            "Hệ thống tản nhiệt tốt, máy không bị nóng khi chơi game dài."
        ],
        cons: [
            "Rất nặng (2.4kg) kèm cục sạc to như viên gạch.",
            "Pin rất nhanh hết khi chơi game, cần cắm sạc thường xuyên.",
            "Giá cao nhất trong danh sách gaming phổ thông."
        ],
        upgradeable: true,
        scoreByUseCase: { it: 85, finance: 20, design: 55, office: 20, gaming: 95, creator: 82, firsttime: 30 }
    },
    {
        id: "l8",
        name: "Dell XPS 13 9315",
        brand: "Dell",
        price: 26500000,
        priceFormatted: "26.500.000đ",
        cpu: "Intel Core i5-1230U",
        cpuLevel: 2,
        ram: "16GB",
        ramValue: 16,
        ssd: "512GB",
        ssdValue: 512,
        gpu: "Intel Iris Xe",
        hasDiscreteGPU: false,
        screen: "13.4 inch FHD+",
        hasColorScreen: false,
        battery: "51Wh",
        batteryLevel: 3,
        weight: "1.17 kg",
        weightValue: 1.17,
        weightLevel: 1,
        warranty: "12 tháng",
        image: "https://placehold.co/400x300/e2e8f0/64748b?text=Dell+XPS+13",
        suitableFor: ["office", "finance", "it"],
        tags: ["lightweight", "battery_good", "ram_16gb", "ssd_512gb", "durable", "office", "coding", "easy_use"],
        pros: [
            "Siêu nhẹ (1.17kg), nhẹ nhất trong các laptop Windows, đặt vào túi như không có.",
            "Thiết kế vỏ nhôm cực sang, màn hình viền siêu mỏng trông rất đẳng cấp.",
            "Pin tốt, dùng văn phòng được 8 tiếng.",
            "Bàn phím và touchpad rất xuất sắc."
        ],
        cons: [
            "Giá đắt so với cấu hình nhận được.",
            "Rất ít cổng kết nối (chỉ có 2 USB-C).",
            "Màn hình nhỏ 13.4 inch, không tiện khi làm Excel nhiều."
        ],
        upgradeable: false,
        scoreByUseCase: { it: 65, finance: 80, design: 40, office: 85, gaming: 5, creator: 45, firsttime: 68 }
    },
    {
        id: "l9",
        name: "MSI Modern 14",
        brand: "MSI",
        price: 11500000,
        priceFormatted: "11.500.000đ",
        cpu: "Intel Core i3-1215U",
        cpuLevel: 1,
        ram: "8GB",
        ramValue: 8,
        ssd: "512GB",
        ssdValue: 512,
        gpu: "Intel UHD Graphics",
        hasDiscreteGPU: false,
        screen: "14 inch FHD IPS",
        hasColorScreen: false,
        battery: "39Wh",
        batteryLevel: 1,
        weight: "1.4 kg",
        weightValue: 1.4,
        weightLevel: 1,
        warranty: "12 tháng",
        image: "https://placehold.co/400x300/e2e8f0/64748b?text=MSI+Modern+14",
        suitableFor: ["finance", "firsttime", "office"],
        tags: ["lightweight", "value_for_money", "office", "easy_use", "ssd_512gb"],
        pros: [
            "Thiết kế nhỏ gọn, đẹp mắt trong tầm giá rẻ.",
            "Đủ dùng cho Word, Excel, lướt web, học online.",
            "Có thể nâng cấp RAM dễ dàng."
        ],
        cons: [
            "Pin hẻo nhất danh sách, chỉ khoảng 3–4 tiếng.",
            "Màn hình màu sắc hơi nhạt.",
            "CPU i3 yếu, không làm được việc nặng."
        ],
        upgradeable: true,
        scoreByUseCase: { it: 25, finance: 60, design: 15, office: 58, gaming: 5, creator: 10, firsttime: 65 }
    },
    {
        id: "l10",
        name: "MacBook Pro M3 14 inch",
        brand: "Apple",
        price: 39900000,
        priceFormatted: "39.900.000đ",
        cpu: "Apple M3",
        cpuLevel: 4,
        ram: "8GB",
        ramValue: 8,
        ssd: "512GB",
        ssdValue: 512,
        gpu: "10-core GPU tích hợp",
        hasDiscreteGPU: false,
        screen: "14.2 inch Liquid Retina XDR",
        hasColorScreen: true,
        battery: "70Wh",
        batteryLevel: 3,
        weight: "1.55 kg",
        weightValue: 1.55,
        weightLevel: 2,
        warranty: "12 tháng",
        image: "https://placehold.co/400x300/e2e8f0/64748b?text=MacBook+Pro+M3",
        suitableFor: ["creator", "design", "it", "office"],
        tags: ["cpu_strong", "color_screen", "battery_good", "durable", "design", "coding", "creator", "office"],
        pros: [
            "Màn hình Liquid Retina XDR đẹp nhất trên laptop, màu cực chuẩn cho thiết kế.",
            "Chip M3 render video cực nhanh, thậm chí nhanh hơn laptop Windows đắt tiền.",
            "Pin dùng thoải mái cả ngày làm việc không cần sạc.",
            "Loa cực hay, touchpad tốt nhất thị trường."
        ],
        cons: [
            "Giá cao nhất trong danh sách.",
            "RAM 8GB hơi ít, muốn 16GB phải bù thêm rất nhiều tiền.",
            "Không chơi được game Windows.",
            "Không nâng cấp RAM hay SSD."
        ],
        upgradeable: false,
        scoreByUseCase: { it: 72, finance: 65, design: 88, office: 80, gaming: 10, creator: 90, firsttime: 55 }
    },
    {
        id: "l11",
        name: "MSI Thin GF63",
        brand: "MSI",
        price: 19500000,
        priceFormatted: "19.500.000đ",
        cpu: "Intel Core i5-12450H",
        cpuLevel: 3,
        ram: "16GB",
        ramValue: 16,
        ssd: "512GB",
        ssdValue: 512,
        gpu: "RTX 4050 6GB",
        hasDiscreteGPU: true,
        screen: "15.6 inch FHD 144Hz",
        hasColorScreen: false,
        battery: "51Wh",
        batteryLevel: 2,
        weight: "1.86 kg",
        weightValue: 1.86,
        weightLevel: 2,
        warranty: "24 tháng",
        image: "https://placehold.co/400x300/e2e8f0/64748b?text=MSI+Thin+GF63",
        suitableFor: ["gaming", "it", "creator"],
        tags: ["gpu_dedicated", "ram_16gb", "ssd_512gb", "cpu_strong", "high_refresh_rate", "cooling_good", "value_for_money", "coding"],
        pros: [
            "Card RTX 4050 6GB đủ mạnh chơi game trung đến nặng mượt mà.",
            "Mỏng và nhẹ hơn các laptop gaming khác (1.86kg).",
            "RAM 16GB và SSD 512GB, thoải mái cho cả game lẫn lập trình.",
            "Giá tốt hơn Acer Nitro với cấu hình tương đương."
        ],
        cons: [
            "Vỏ nhựa, cảm giác không sang bằng laptop văn phòng cao cấp.",
            "Pin chỉ 3–4 tiếng khi dùng nhẹ, chơi game cần cắm sạc.",
            "Màn hình màu không đẹp."
        ],
        upgradeable: true,
        scoreByUseCase: { it: 78, finance: 25, design: 40, office: 28, gaming: 85, creator: 68, firsttime: 38 }
    },
    {
        id: "l12",
        name: "Asus TUF Gaming A15",
        brand: "Asus",
        price: 24500000,
        priceFormatted: "24.500.000đ",
        cpu: "AMD Ryzen 7 7735HS",
        cpuLevel: 4,
        ram: "16GB",
        ramValue: 16,
        ssd: "512GB",
        ssdValue: 512,
        gpu: "RTX 4060 8GB",
        hasDiscreteGPU: true,
        screen: "15.6 inch FHD 144Hz",
        hasColorScreen: false,
        battery: "90Wh",
        batteryLevel: 3,
        weight: "2.2 kg",
        weightValue: 2.2,
        weightLevel: 3,
        warranty: "24 tháng",
        image: "https://placehold.co/400x300/e2e8f0/64748b?text=Asus+TUF+A15",
        suitableFor: ["gaming", "creator", "it"],
        tags: ["gpu_dedicated", "cpu_strong", "ram_16gb", "ssd_512gb", "cooling_good", "high_refresh_rate", "durable", "battery_good", "coding"],
        pros: [
            "Ryzen 7 + RTX 4060: combo cực mạnh cho game nặng và dựng video.",
            "Pin 90Wh, to nhất phân khúc gaming, chơi game được 3–4 tiếng.",
            "Bền bỉ, thiết kế military-grade, chịu va đập tốt hơn nhiều laptop thường.",
            "Tản nhiệt cực tốt, máy không bị nóng dù chơi game dài."
        ],
        cons: [
            "Máy nặng (2.2kg), không tiện mang đi mỗi ngày.",
            "Thiết kế gaming hơi cứng, không phù hợp môi trường văn phòng.",
            "Màn hình màu không đủ tốt cho thiết kế chuyên nghiệp."
        ],
        upgradeable: true,
        scoreByUseCase: { it: 85, finance: 18, design: 48, office: 20, gaming: 92, creator: 80, firsttime: 32 }
    },
    {
        id: "l13",
        name: "HP Envy x360 14",
        brand: "HP",
        price: 22000000,
        priceFormatted: "22.000.000đ",
        cpu: "AMD Ryzen 5 7530U",
        cpuLevel: 2,
        ram: "16GB",
        ramValue: 16,
        ssd: "512GB",
        ssdValue: 512,
        gpu: "AMD Radeon Graphics",
        hasDiscreteGPU: false,
        screen: "14 inch FHD OLED 2-in-1",
        hasColorScreen: true,
        battery: "66Wh",
        batteryLevel: 3,
        weight: "1.5 kg",
        weightValue: 1.5,
        weightLevel: 1,
        warranty: "12 tháng",
        image: "https://placehold.co/400x300/e2e8f0/64748b?text=HP+Envy+x360",
        suitableFor: ["design", "finance", "office", "creator"],
        tags: ["lightweight", "battery_good", "color_screen", "ram_16gb", "ssd_512gb", "office", "design", "balanced", "durable", "easy_use"],
        pros: [
            "Màn hình OLED cảm ứng, gập 360 độ, dùng như máy tính bảng khi cần.",
            "Màu sắc OLED cực đẹp, rất phù hợp thiết kế Canva, Figma hay chỉnh ảnh.",
            "Pin trâu đến 10 tiếng sử dụng thực tế.",
            "Nhẹ và đẹp, sang chảnh trong môi trường học tập hay văn phòng."
        ],
        cons: [
            "Không có card đồ họa rời, không phù hợp game nặng hoặc render 3D.",
            "Giá khá cao so với cấu hình.",
            "Bản lề 360 thêm trọng lượng so với laptop bình thường."
        ],
        upgradeable: false,
        scoreByUseCase: { it: 60, finance: 82, design: 78, office: 82, gaming: 10, creator: 70, firsttime: 75 }
    },
    {
        id: "l14",
        name: "Dell Inspiron 15 3520",
        brand: "Dell",
        price: 13500000,
        priceFormatted: "13.500.000đ",
        cpu: "Intel Core i5-1235U",
        cpuLevel: 2,
        ram: "8GB",
        ramValue: 8,
        ssd: "512GB",
        ssdValue: 512,
        gpu: "Intel Iris Xe",
        hasDiscreteGPU: false,
        screen: "15.6 inch FHD",
        hasColorScreen: false,
        battery: "54Wh",
        batteryLevel: 2,
        weight: "1.73 kg",
        weightValue: 1.73,
        weightLevel: 2,
        warranty: "12 tháng",
        image: "https://placehold.co/400x300/e2e8f0/64748b?text=Dell+Inspiron+15",
        suitableFor: ["firsttime", "finance", "office"],
        tags: ["value_for_money", "office", "ssd_512gb", "easy_use", "durable", "excel", "balanced"],
        pros: [
            "Giá tốt, cấu hình đủ dùng cho văn phòng và học tập.",
            "Màn hình lớn 15.6 inch tiện làm Excel hay xem phim.",
            "Bền bỉ, Dell có tiếng về độ tin cậy và bảo hành tốt.",
            "Pin dùng được 6–7 tiếng văn phòng."
        ],
        cons: [
            "RAM 8GB hơi ít nếu mở nhiều ứng dụng.",
            "Thiết kế khá bình thường, nặng hơn các laptop mỏng nhẹ.",
            "Không phù hợp game hay đồ họa nặng."
        ],
        upgradeable: true,
        scoreByUseCase: { it: 45, finance: 72, design: 25, office: 70, gaming: 8, creator: 20, firsttime: 76 }
    },
    {
        id: "l15",
        name: "Lenovo ThinkPad E14 Gen 5",
        brand: "Lenovo",
        price: 20500000,
        priceFormatted: "20.500.000đ",
        cpu: "AMD Ryzen 5 7530U",
        cpuLevel: 2,
        ram: "16GB",
        ramValue: 16,
        ssd: "512GB",
        ssdValue: 512,
        gpu: "AMD Radeon Graphics",
        hasDiscreteGPU: false,
        screen: "14 inch FHD IPS",
        hasColorScreen: false,
        battery: "57Wh",
        batteryLevel: 3,
        weight: "1.57 kg",
        weightValue: 1.57,
        weightLevel: 2,
        warranty: "12 tháng",
        image: "https://placehold.co/400x300/e2e8f0/64748b?text=ThinkPad+E14",
        suitableFor: ["office", "it", "finance"],
        tags: ["ram_16gb", "ssd_512gb", "battery_good", "durable", "office", "coding", "excel", "webcam_good", "upgradeable"],
        pros: [
            "Bàn phím ThinkPad nổi tiếng tốt nhất thị trường, gõ rất sướng.",
            "RAM 16GB, bền bỉ, thương hiệu doanh nghiệp đáng tin cậy.",
            "Webcam và mic chất lượng tốt, phù hợp họp online nhiều.",
            "Dễ nâng cấp RAM và SSD.",
            "Pin tốt, khoảng 8 tiếng sử dụng thực tế."
        ],
        cons: [
            "Thiết kế đơn giản, không đẹp bằng HP hay Apple.",
            "Không phù hợp game hoặc thiết kế đồ họa nặng.",
            "Giá hơi cao so với các máy tầm giá tương tự."
        ],
        upgradeable: true,
        scoreByUseCase: { it: 78, finance: 80, design: 35, office: 88, gaming: 8, creator: 40, firsttime: 70 }
    }
];
